=== schugDev/DB2Redux/files/ARTIKEL.dtd
<!ELEMENT TBLARTIKEL (ARTIKEL+)>
        <!ELEMENT ARTIKEL (ARTNR,ARTBEZ,PREIS,KUEHL,MGE,ANZBO,EDAT?)>
        <!ELEMENT ARTNR (#PCDATA)>
        <!ATTLIST ARTNR DT CDATA #REQUIRED>
        <!ELEMENT ARTBEZ (#PCDATA)>
        <!ATTLIST ARTBEZ DT CDATA #REQUIRED>
        <!ELEMENT PREIS (#PCDATA)>
        <!ATTLIST PREIS DT CDATA #REQUIRED>
        <!ELEMENT KUEHL (#PCDATA)>
        <!ATTLIST KUEHL DT CDATA #REQUIRED>
        <!ELEMENT MGE (#PCDATA)>
        <!ATTLIST MGE DT CDATA #REQUIRED>
        <!ELEMENT ANZBO (#PCDATA)>
        <!ATTLIST ANZBO DT CDATA #REQUIRED>
        <!ELEMENT EDAT (#PCDATA)>
        <!ATTLIST EDAT DT CDATA #REQUIRED>

=== schugDev/DB2Redux/files/ARTIKEL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TBLARTIKEL SYSTEM "ARTIKEL.dtd">

  <TBLARTIKEL>
      <ARTIKEL>
        <ARTNR DT="int">0</ARTNR>
        <ARTBEZ DT="char(30)">Schraubendreher1</ARTBEZ>
        <PREIS DT="decimal(7,2)">4.99</PREIS>
        <KUEHL DT="char(2)">NK</KUEHL>
        <MGE DT="char(30)">1 Mge</MGE>
        <ANZBO DT="char(30)">13</ANZBO>
        <EDAT DT="date">20.05.2019</EDAT>
    </ARTIKEL>
      <ARTIKEL>
        <ARTNR DT="int">0</ARTNR>
        <ARTBEZ DT="char(30)">Schraubendreher1</ARTBEZ>
        <PREIS DT="decimal(7,2)">4.99</PREIS>
        <KUEHL DT="char(2)">NK</KUEHL>
        <MGE DT="char(30)">1 Mge</MGE>
        <ANZBO DT="char(30)">13</ANZBO>
        <EDAT DT="date">20.05.2019</EDAT>
    </ARTIKEL>
    <ARTIKEL>
        <ARTNR DT="int">0</ARTNR>
        <ARTBEZ DT="char(30)">Schraubendreher2</ARTBEZ>
        <PREIS DT="decimal(7,2)">4.99</PREIS>
        <KUEHL DT="char(2)">NK</KUEHL>
        <MGE DT="char(30)">1 Mge</MGE>
        <ANZBO DT="char(30)">13</ANZBO>
        <EDAT DT="date">20.05.2019</EDAT>
    </ARTIKEL>
     <ARTIKEL>
        <ARTNR DT="int">0</ARTNR>
        <ARTBEZ DT="char(30)">Schraubendreher3</ARTBEZ>
        <PREIS DT="decimal(7,2)">4.99</PREIS>
        <ggf>xxx</ggf>
        <KUEHL DT="char(2)">NK</KUEHL>
        <MGE DT="char(30)">1 Mge</MGE>
        <ANZBO DT="char(30)">13</ANZBO>
        <EDAT DT="date">20.05.2019</EDAT>
    </ARTIKEL>
     <ARTIKEL>
        <ARTNR DT="int">0</ARTNR>
        <ARTBEZ DT="char(30)">Schraubendreher4</ARTBEZ>
        <PREIS DT="decimal(7,2)">4.99</PREIS>
        <KUEHL DT="char(2)">NK</KUEHL>
        <MGE DT="char(30)">1 Mge</MGE>
        <ANZBO DT="char(30)">13</ANZBO>
        <EDAT DT="date">20.05.2019</EDAT>
    </ARTIKEL>
    

</TBLARTIKEL>
